[project]
name = "awsops"
version = "0.1.0"
authors = [{name = "Daniel Hollarek", email = "daniel.hollarek@googlemail.com"}]
description = "Really simple AWS"
readme = "readme.md"
dependencies = ['boto3', 'botocore']

#urls = { "repository" = "https://github.com/Somerandomguy10111/..." }
